{
    "openapi": "3.0.0",
    "info": {
      "title": "VTEX Shipping Network API",
      "contact": {},
      "description": "**[VTEX Shipping Network](https://developers.vtex.com/docs/guides/vtex-shipping-network)** connects carriers and store owners to deliver better freight costs, and a simpler and smarter logistics operation. VTEX Shipping Network uses the following steps during a package's tracking process: \r\n\r\n- **Notification:** OMS notifies the carrier that a package is being dispatched. \r\n\r\n- **Tracking:** tracking of the package begins, and is repeated in cycles, until its final delivery. \r\n\r\nFor carriers to integrate with VTEX Shipping Network's Hub, our main system, it is necessary to develop apps in VTEX IO, and associate API routes with them. The carrier's apps integrate with the hub, that in turn are connected to other VTEX systems, fulfilling the steps cited above. \r\n\r\nCheckout our [Integration Guide](https://developers.vtex.com/docs/guides/vtex-shipping-network) to learn more.",
      "version": "1.0"
    },
    "servers": [
      {
        "url": "https://app.io.vtex.com",
        "description": "VTEX server URL.",
        "variables": {}
      }
    ],
    "paths": {
      "/{app_name}/v{app_version}/{account}/{workspace}/notify": {
        "post": {
          "tags": [
            "Notification"
          ],
          "summary": "Notify carrier with app",
          "description": "This endpoint notifies the carrier about a dispatch order by calling the `vtex.carrier-notifier app`. When the call is made, the following data is sent: \n\n- Dispatched packages information. \n\n- Fiscal information about the carrier notified. \n\n- Carrier's contact email. \n\nThe call's response includes all tracking data and each package's ID generated by the notification made to the carrier.",
          "operationId": "NotifyCarrierwithApp",
          "parameters": [
            {
              "name": "app_name",
              "in": "path",
              "description": "Name of the app developed by the carrier's integration.",
              "required": true,
              "style": "simple",
              "schema": {
                "type": "string",
                "default": "{{app name}}"
              }
            },
            {
              "name": "app_version",
              "in": "path",
              "description": "Version of the app developed by the carrier's integration.",
              "required": true,
              "style": "simple",
              "schema": {
                "type": "string",
                "default": "{{version}}"
              }
            },
            {
              "name": "account",
              "in": "path",
              "description": "VTEX account dispatching the package.",
              "required": true,
              "style": "simple",
              "schema": {
                "type": "string",
                "default": "VTEX Store example"
              }
            },
            {
                "name": "workspace",
                "in": "path",
                "description": "Workspace used in VTEX IO. ",
                "required": true,
                "style": "simple",
                "schema": {
                  "type": "string",
                  "default": "master"
                }
              }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NotifyCarrierwithAppRequest"
                },
                "example": {
                  "account": {
                    "name": "Ltda",
                    "accountName": "{{account}}",
                    "isOperating": true,
                    "defaultUrl": null,
                    "district": null,
                    "country": "Brasil",
                    "complement": null,
                    "companyName": "LTDA",
                    "cnpj": "00000000000000",
                    "city": null,
                    "address": null,
                    "number": null,
                    "postalCode": null,
                    "state": null,
                    "telephone": null,
                    "tradingName": "tradingName"
                  },
                  "email": "email",
                  "dispatchOrder": {
                    "id": "653560c2-7965-4614-a730-8e45c89bf284",
                    "packageIds": [
                      "6529cd28-6fd1-4b95-8397-5fad0a79d41c"
                    ],
                    "sender": {
                      "cnpj": "00000000000000",
                      "fantasyName": null,
                      "stateRegistration": null,
                      "id": null,
                      "name": "LTDA",
                      "address": {
                        "postalCode": "03475015",
                        "country": {
                          "code": "BRA",
                          "name": "Brasil"
                        },
                        "subregion1": {
                          "code": "SP",
                          "name": "S達o Paulo"
                        },
                        "subregion2": {
                          "code": "S達o Paulo",
                          "name": "S達o Paulo"
                        },
                        "subregion3": {
                          "code": "Vila Antonieta",
                          "name": "Vila Antonieta"
                        },
                        "street": "Rua Exemplo",
                        "number": "01",
                        "complement": "",
                        "location": null
                      },
                      "email": null,
                      "phone":"999999999"
                    },
                    "carrier": {
                      "cnpj": "00000000000000",
                      "fantasyName": "carrier",
                      "stateRegistration": "096/3624636",
                      "id": "vtexlog_exemplo",
                      "name": "Carrier LTDA.",
                      "address": {
                        "postalCode": "90200001",
                        "country": {
                          "code": "BRA",
                          "name": "Brasil"
                        },
                        "subregion1": {
                          "code": "RS",
                          "name": "Rio Grande do Sul"
                        },
                        "subregion2": {
                          "code": "Porto_Alegre",
                          "name": "Porto Alegre"
                        },
                        "subregion3": {
                          "code": "Anchieta",
                          "name": "Anchieta"
                        },
                        "street": "Rua Exemplo",
                        "number": "01",
                        "complement": "Pavilh達o 6",
                        "location": null
                      },
                      "email": "email",
                      "phone": "+5511111111111"
                    }
                  }
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "OK",
              "headers": {}
            }
          },
          "deprecated": false
        }
      },
      "/{app_name}/v{app_version}/{account}/{workspace}/tracking": {
        "post": {
          "tags": [
            "Tracking"
          ],
          "summary": "Tracking events with app",
          "description": "This endpoint is called by the hub to  obtain the tracking events of a series of tracking numbers. This call's request updates the events of a list of tracking codes, for packages that are still pending delivery. The expected response is an object contaning the tracking information and the package's notification ID for every `packageID`.",
          "operationId": "TrackingEvents",
          "parameters": [
            {
                "name": "app_name",
                "in": "path",
                "description": "Name of the app developed by the carrier's integration.",
                "required": true,
                "style": "simple",
                "schema": {
                  "type": "string",
                  "default": "{{app name}}"
                }
              },
              {
                "name": "app_version",
                "in": "path",
                "description": "Version of the app developed by the carrier's integration.",
                "required": true,
                "style": "simple",
                "schema": {
                  "type": "string",
                  "default": "{{version}}"
                }
              },
              {
                "name": "account",
                "in": "path",
                "description": "VTEX account dispatching the package.",
                "required": true,
                "style": "simple",
                "schema": {
                  "type": "string",
                  "default": "VTEX Store example"
                }
              },
            {
                "name": "workspace",
                "in": "path",
                "description": "Workspace used in VTEX IO. ",
                "required": true,
                "style": "simple",
                "schema": {
                  "type": "string",
                  "default": "master"
                }
              }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/TrackingEventsRequest"
                  },
                  "description": "Array containing tracking information.",
                  "example": [
                    {
                      "trackingNumber": "BR000000000"
                    }
                  ]
                },
                "example": [
                  {
                    "trackingNumber": "BR000000000"
                  }
                ]
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "OK",
              "headers": {}
            }
          },
          "deprecated": false
        }
      }
    },
    "security": [
    {
      "appKey": [],
      "appToken": []
    }
    ],    
    "components": {
        "securitySchemes": {
            "appKey": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppKey"
            },
            "appToken": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppToken"
            }
        },
      "schemas": {
        "Account": {
          "title": "Account",
          "required": [
            "name",
            "accountName",
            "isOperating",
            "defaultUrl",
            "district",
            "country",
            "complement",
            "companyName",
            "cnpj",
            "city",
            "address",
            "number",
            "postalCode",
            "state",
            "telephone",
            "tradingName"
          ],
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "Inserted name.",
              "example": "Ltda"
            },
            "accountName": {
              "type": "string",
              "description": "Name of the VTEX Account dispatching the package.",
              "example": "mystore"
            },
            "isOperating": {
              "type": "boolean",
              "description": "Whether the store is operating or not.",
              "example": true
            },
            "defaultUrl": {
              "type": "string",
              "nullable": true,
              "description": "Retrieved from VTEX's License Manager.",
              "example": "https://url.example.com"
            },
            "district": {
              "type": "string",
              "nullable": true,
              "description": "District where the VTEX store dispatching the package is located.",
              "default": "District name"
            },
            "country": {
              "type": "string",
              "description": "Country where the VTEX store, dispatching the package, is located.",
              "default": "Brasil"
            },
            "complement": {
              "type": "string",
              "nullable": true,
              "description": "Complement for the VTEX store's address.",
              "default": "Second floor"
            },
            "companyName": {
              "type": "string",
              "description": "Name of the VTEX store responsible for the package.",
              "default": "VTEX Store 1"
            },
            "cnpj": {
              "type": "string",
              "description": "CNPJ code of the VTEX store responsible for the package.",
              "default": "00000000000000"
            },
            "city": {
              "type": "string",
              "nullable": true,
              "description": "City where the VTEX store responsible for the package is located.",
              "default": "Rio de Janeiro"
            },
            "address": {
              "type": "string",
              "nullable": true,
              "description": "Address where the VTEX store responsible for the package is located.",
              "default": "VTEX Street"
            },
            "number": {
              "type": "string",
              "nullable": true,
              "description": "Number of the address related to the `address` field.",
              "default": "26"
            },
            "postalCode": {
              "type": "string",
              "nullable": true,
              "description": "ZIP code of the VTEX store responsible for the package.",
              "default": "12345-678"
            },
            "state": {
              "type": "string",
              "nullable": true,
              "description": "State of the address belonging to the VTEX store responsible for the package.",
              "default": "RJ"
            },
            "telephone": {
              "type": "string",
              "nullable": true,
              "description": "Telephone number of the VTEX store responsible for the package.",
              "default": "99999999"
            },
            "tradingName": {
              "type": "string",
              "description": "Trading name of the VTEX store responsible for the package.",
              "default": "Trading name"
            }
          },
          "description": "Account information.",
          "example": {
            "name": "Ltda",
            "accountName": "{{account}}",
            "isOperating": true,
            "defaultUrl": null,
            "district": null,
            "country": "Brasil",
            "complement": null,
            "companyName": "LTDA",
            "cnpj": "00000000000000",
            "city": null,
            "address": null,
            "number": null,
            "postalCode": null,
            "state": null,
            "telephone": null,
            "tradingName": "tradingName"
          }
        },
        "Address": {
          "title": "Address",
          "required": [
            "postalCode",
            "country",
            "subregion1",
            "subregion2",
            "subregion3",
            "street",
            "number",
            "complement",
            "location"
          ],
          "type": "object",
          "properties": {
            "postalCode": {
                "type": "string",
                "nullable": true,
                "description": "ZIP code of the package's recipient.",
                "default": "12345-678"
              },
            "country": {
              "$ref": "#/components/schemas/Country"
            },
            "subregion1": {
              "$ref": "#/components/schemas/Subregion1"
            },
            "subregion2": {
              "$ref": "#/components/schemas/Subregion2"
            },
            "subregion3": {
              "$ref": "#/components/schemas/Subregion3"
            },
            "street": {
              "type": "string",
              "description": "Recipient's address.",
              "default":"Street example"
            },
            "number": {
              "type": "string",
              "description": "Number of the recipient's address.",
              "default":"1"
            },
            "complement": {
              "type": "string",
              "nullable": true,
              "description": "Complement for the recipient's address.",
              "default":"A"
            },
            "location": {
              "$ref": "#/components/schemas/Location"
            }
          },
          "example": {
            "postalCode": "00000-000",
            "country": {
              "code": "BRA",
              "name": "BRA"
            },
            "subregion1": {
              "code": "SP",
              "name": "SP"
            },
            "subregion2": {
              "code": "S達o Paulo",
              "name": "S達o Paulo"
            },
            "subregion3": {
              "code": "Burgo Paulista",
              "name": "Burgo Paulista"
            },
            "street": "Rua Exempo",
            "number": "01",
            "complement": null,
            "location": {
              "lat": -46.485820770263672,
              "lng": -23.521709442138672
            }
          }
        },
        "Country": {
          "title": "Country",
          "required": [
            "code",
            "name"
          ],
          "type": "object",
          "properties": {
            "code": {
              "type": "string",
              "description": "Country's three-digit identifying code, from the recipient's address.",
              "default":"BRA"
            },
            "name": {
              "type": "string",              
              "description": "Country's name, from the recipient's address.",
              "default":"Brasil"
            }
          },
          "example": {
            "code": "BRA",
            "name": "BRA"
          }
        },
        "Subregion1": {
          "title": "State",
          "required": [
            "code",
            "name"
          ],
          "type": "object",
          "properties": {
            "code": {
              "type": "string",
              "description": "State's code, from the recipient's address.",
              "default":"SP"
            },
            "name": {
              "type": "string",
              "description": "State's name, from the recipient's address.",
              "default":"Sao Paulo"
            }
          },
          "example": {
            "code": "SP",
            "name": "SP"
          }
        },
        "Subregion2": {
            "title": "City",
            "required": [
              "code",
              "name"
            ],
            "type": "object",
            "properties": {
              "code": {
                "type": "string",
                "description": "City's code, from the recipient's address.",
                "default":"SP"
              },
              "name": {
                "type": "string",
                "description": "City's name, from the recipient's address.",
                "default":"Sao Paulo"
              }
            },
            "example": {
              "code": "SP",
              "name": "S達o Paulo"
            }
        },
        "Subregion3": {
        "title": "Neighborhood",
        "required": [
            "code",
            "name"
        ],
        "type": "object",
        "properties": {
            "code": {
            "type": "string",
            "description": "Neighborhood's code, from the recipient's address.",
            "default":"Neighborhood example"

            },
            "name": {
            "type": "string",
            "description": "Neighborhood's name, from the recipient's address.",
            "default":"Neighborhood example"
            }
        },
        "example": {
            "code": "Vila Antonieta",
            "name": "Vila Antonieta"
        }
        },          
        "Location": {
          "title": "Location",
          "required": [
            "lat",
            "lng"
          ],
          "type": "object",
          "nullable": true,
          "properties": {
            "lat": {
              "type": "number",
              "description": "Latitude number of the address' geolocation coordinates.",
              "default":-46.485820770263672
            },
            "lng": {
              "type": "number",              
              "description": "Longitude number of the address' geolocation coordinates.",
              "default":-23.521709442138672
            }
          },
          "example": {
            "lat": -46.485820770263672,
            "lng": -23.521709442138672
          }
        },
        "NotifyCarrierwithAppRequest": {
          "title": "NotifyCarrierwithAppRequest",
          "required": [
            "email",
            "dispatchOrder",
            "account"
          ],
          "type": "object",
          "properties": {
            "account":{
              "$ref": "#/components/schemas/Account"    
            },  
            "email": {
              "type": "string",
              "description": "Fill in this field if you wish to send the generated file for an email besides the ones already involved in the operation, like the carrier and VTEX account's email.",
              "default":"email"
            },
            "dispatchOrder": {
              "$ref": "#/components/schemas/DispatchOrder"
            }
          },
          "example": {
            "account": {
              "name": "Ltda",
              "accountName": "{{account}}",
              "isOperating": true,
              "defaultUrl": null,
              "district": null,
              "country": "Brasil",
              "complement": null,
              "companyName": "LTDA",
              "cnpj": "00000000000000",
              "city": null,
              "address": null,
              "number": null,
              "postalCode": null,
              "state": null,
              "telephone": null,
              "tradingName": "tradingName"
            },
            "email": "email",
            "dispatchOrder": {
              "id": "653560c2-7965-4614-a730-8e45c89bf284",
              "packageIds": [
                "6529cd28-6fd1-4b95-8397-5fad0a79d41c"
              ],
              "sender": {
                "cnpj": "00000000000000",
                "fantasyName": null,
                "stateRegistration": null,
                "id": null,
                "name": "LTDA",
                "address": {
                  "postalCode": "03475015",
                  "country": {
                    "code": "Brasil",
                    "name": "Brasil"
                  },
                  "subregion1": {
                    "code": "SP",
                    "name": "SP"
                  },
                  "subregion2": {
                    "code": "S達o Paulo",
                    "name": "S達o Paulo"
                  },
                  "subregion3": {
                    "code": "Vila Antonieta",
                    "name": "Vila Antonieta"
                  },
                  "street": "Rua Exemplo",
                  "number": "01",
                  "complement": "",
                  "location": null
                },
                "email": null,
                "phone": "+5511111111111"
              },
              "carrier": {
                "cnpj": "00000000000000",
                "fantasyName": "carrier",
                "stateRegistration": "096/3624636",
                "id": "vtexlog_exemplo",
                "name": "Carrier LTDA.",
                "address": {
                  "postalCode": "90200001",
                  "country": {
                    "code": "BRA",
                    "name": "Brasil"
                  },
                  "subregion1": {
                    "code": "RS",
                    "name": "Rio Grande do Sul"
                  },
                  "subregion2": {
                    "code": "Porto_Alegre",
                    "name": "Porto Alegre"
                  },
                  "subregion3": {
                    "code": "Anchieta",
                    "name": "Anchieta"
                  },
                  "street": "Rua Exemplo",
                  "number": "01",
                  "complement": "Pavilh達o 6",
                  "location": null
                },
                "email": "email",
                "phone": "+5511111111111"
              }
            }
          }
        },
        "DispatchOrder": {
          "title": "DispatchOrder",
          "required": [
            "id",
            "packageIds",
            "sender",
            "carrier"
          ],
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "description": "ID of the dispatch Order.",
              "default":"653560c2-7965-4614-a730-8e45c89bf284"
            },
            "packageIds": {
                "type": "array",
                "description": "Array with package IDs",
                "items": {
                    "type": "string",
                    "description": "Identification codes of the packages.",
                    "example": "6529cd28-6fd1-4b95-8397-5fad0a79d41c"
                }
            },
            "sender": {
              "$ref": "#/components/schemas/Sender"
            },
            "carrier": {
              "$ref": "#/components/schemas/Carrier"
            }
          },
          "example": {
            "id": "653560c2-7965-4614-a730-8e45c89bf284",
            "packageIds": [
              "6529cd28-6fd1-4b95-8397-5fad0a79d41c"
            ],
            "sender": {
              "cnpj": "00000000000000",
              "fantasyName": null,
              "stateRegistration": null,
              "id": null,
              "name": "LTDA",
              "address": {
                "postalCode": "03475015",
                "country": {
                  "code": "Brasil",
                  "name": "Brasil"
                },
                "subregion1": {
                  "code": "SP",
                  "name": "SP"
                },
                "subregion2": {
                  "code": "S達o Paulo",
                  "name": "S達o Paulo"
                },
                "subregion3": {
                  "code": "Vila Antonieta",
                  "name": "Vila Antonieta"
                },
                "street": "Rua Exemplo",
                "number": "01",
                "complement": "",
                "location": null
              },
              "email": null,
              "phone": "+5511111111111"
            },
            "carrier": {
              "cnpj": "00000000000000",
              "fantasyName": "carrier",
              "stateRegistration": "096/3624636",
              "id": "vtexlog_exemplo",
              "name": "Carrier LTDA.",
              "address": {
                "postalCode": "90200001",
                "country": {
                  "code": "BRA",
                  "name": "Brasil"
                },
                "subregion1": {
                  "code": "RS",
                  "name": "Rio Grande do Sul"
                },
                "subregion2": {
                  "code": "Porto_Alegre",
                  "name": "Porto Alegre"
                },
                "subregion3": {
                  "code": "Anchieta",
                  "name": "Anchieta"
                },
                "street": "Rua Exemplo",
                "number": "01",
                "complement": "Pavilh達o 6",
                "location": null
              },
              "email": "email",
              "phone": "+5511111111111"
            }
          }
        },
        "Sender": {
          "title": "Sender",
          "description": "User's logged account in the VTEX store.",
          "required": [
            "cnpj",
            "fantasyName",
            "stateRegistration",
            "id",
            "name",
            "address",
            "email",
            "phone"
          ],
          "type": "object",
          "properties": {
            "cnpj": {
                "type": "string",
                "description": "CNPJ code of the VTEX account responsible for sending the package.",
                "default": "00000000000000"
              },
            "fantasyName": {
              "type": "string",
              "description": "Fantasy name of the VTEX account responsible for sending the package.",
              "default":"Carrier 123",
              "nullable": true
            },
            "stateRegistration": {
              "type": "string",
              "description": "State Registration code of the VTEX account responsible for sending the package.",
              "default":"9843759348",
              "nullable": true
            },
            "id": {
              "type": "string",              
              "description": "VTEX account's ID.",
              "default":"accountId",
              "nullable": true
            },
            "name": {
              "type": "string",              
              "description": "Name of the VTEX account responsible for sending the package.",
              "default":"Store LTDA"
            },
            "address": {
              "$ref": "#/components/schemas/Address"
            },
            "email": {
              "type": "string",              
              "description": "Email of the VTEX account responsible for sending the package.",
              "default":"email@email.com",
              "nullable": true
            },
            "phone": {
                "type": "string",
                "description": "Sender's contact number",
                "default": "+5511111111111",
                "nullable": true
              }
          },
          "example": {
            "cnpj": "00000000000000",
            "fantasyName": null,
            "stateRegistration": null,
            "id": null,
            "name": "LTDA",
            "address": {
              "postalCode": "03475015",
              "country": {
                "code": "Brasil",
                "name": "Brasil"
              },
              "subregion1": {
                "code": "SP",
                "name": "SP"
              },
              "subregion2": {
                "code": "S達o Paulo",
                "name": "S達o Paulo"
              },
              "subregion3": {
                "code": "Vila Antonieta",
                "name": "Vila Antonieta"
              },
              "street": "Rua Exemplo",
              "number": "01",
              "complement": "",
              "location": null
            },
            "email": null,
            "phone": "+5511111111111"
          }
        },
        "Carrier": {
          "title": "Carrier",
          "required": [
            "cnpj",
            "fantasyName",
            "stateRegistration",
            "id",
            "name",
            "address",
            "email",
            "phone"
          ],
          "type": "object",
          "properties": {
            "cnpj": {
              "type": "string",              
              "description": "Carrier's CNPJ.",
              "default":"00000000000000"
            },
            "fantasyName": {
              "type": "string",              
              "description": "Carrier's fantasy name.",
              "default":"Carrier A"
            },
            "stateRegistration": {
              "type": "string",              
              "description": "Carrier's state registration number.",
              "default":"843904894875"
            },
            "id": {
              "type": "string",              
              "description": "Carrier's ID.",
              "default":"vtexShippinNetwork_example"
            },
            "name": {
              "type": "string",              
              "description": "Carrier's company name.",
              "default":"Carrier LTDA"
            },
            "address": {
              "$ref": "#/components/schemas/Address"
            },
            "email": {
              "type": "string",              
              "description": "Carrier's email address.",
              "default":"email@example.com"
            },
            "phone": {
                "type": "string",
                "description": "Carrier's contact number.",
                "default": "+5511111111111",
                "nullable": true
              }
          },
          "example": {
            "cnpj": "00000000000000",
            "fantasyName": "carrier",
            "stateRegistration": "096/3624636",
            "id": "vtexlog_exemplo",
            "name": "Carrier LTDA.",
            "address": {
              "postalCode": "90200001",
              "country": {
                "code": "BRA",
                "name": "Brasil"
              },
              "subregion1": {
                "code": "RS",
                "name": "Rio Grande do Sul"
              },
              "subregion2": {
                "code": "Porto_Alegre",
                "name": "Porto Alegre"
              },
              "subregion3": {
                "code": "Anchieta",
                "name": "Anchieta"
              },
              "street": "Rua Exemplo",
              "number": "01",
              "complement": "Pavilh達o 6",
              "location": null
            },
            "email": "email",
            "phone": "+5511111111111"
          }
        },
        "TrackingEventsRequest": {
          "title": "TrackingEventsRequest",
          "required": [
            "trackingNumber"
          ],
          "type": "object",
          "properties": {
            "trackingNumber": {
              "type": "string",
              "description":"Shipping's tracking identification code.",
              "default": "BR000000000"
            }
          },
          "example": {
            "trackingNumber": "BR000000000"
          }
        }
      }
    },
    "tags": [
      {
        "name": "Notification"
      },
      {
        "name": "Tracking"
      }
    ]
  }